### ISSUE TITLE
nxdomain on bad bad home base causes supervisor crashing

### ISSUE THREAD

**Issue by elliottneilclark** [batteries-included/batteries-included#1027]
```
{"message":"K8s.Client.Runner.Stream.Watch Bookmark received","time":"2024-10-14T01:08:03.880Z","metadata":{},"severity":"debug"}
{"message":"Failed to send host report: :nxdomain","time":"2024-10-14T01:08:30.750Z","metadata":{},"severity":"error"}
{"message":"Unexpected error trying to send host report: {:error, {:error, :nxdomain}}","time":"2024-10-14T01:08:30.750Z","metadata":{},"severity":"error"}
{"message":"Reporting usage to Elixir.KubeServices.ET.HomeBaseClient","time":"2024-10-14T01:08:31.859Z","metadata":{},"severity":"info"}
{"message":"Failed to send host report: :nxdomain","time":"2024-10-14T01:08:31.875Z","metadata":{},"severity":"error"}
{"message":"Unexpected error trying to send host report: {:error, {:error, :nxdomain}}","time":"2024-10-14T01:08:31.875Z","metadata":{},"severity":"error"}
{"message":"Sending usage to https://home.prod.batteriesincl.com/api/v1","time":"2024-10-14T01:08:31.889Z","metadata":{},"severity":"info"}
{"message":"Failed to send usage report: :nxdomain","time":"2024-10-14T01:08:31.901Z","metadata":{},"severity":"error"}
{"message":"Failed to send usage: :nxdomain","time":"2024-10-14T01:08:31.901Z","metadata":{},"severity":"error"}
{"message":"GenServer KubeServices.ET.Usage terminating\n** (MatchError) no match of right hand side value: {:error, :nxdomain}\n    (kube_services 0.24.0) lib/kube_services/et/usage.ex:48: KubeServices.ET.Usage.handle_info/2\n    (stdlib 6.1) gen_server.erl:2345: :gen_server.try_handle_info/3\n    (stdlib 6.1) gen_server.erl:2433: :gen_server.handle_msg/6\n    (stdlib 6.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3\nLast message: :report\nState: %KubeServices.ET.Usage.State{home_client: KubeServices.ET.HomeBaseClient, sleep_time: 271160}","time":"2024-10-14T01:08:31.902Z","metadata":{},"severity":"error"}
{"message":"Process KubeServices.ET.Usage (#PID<0.462.0>) terminating\n** (MatchError) no match of right hand side value: {:error, :nxdomain}\n    (kube_services 0.24.0) lib/kube_services/et/usage.ex:48: KubeServices.ET.Usage.handle_info/2\n    (stdlib 6.1) gen_server.erl:2345: :gen_server.try_handle_info/3\n    (stdlib 6.1) gen_server.erl:2433: :gen_server.handle_msg/6\n    (stdlib 6.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3\nInitial Call: KubeServices.ET.Usage.init/1\nAncestors: [#PID<0.460.0>, KubeServices.Batteries.DynamicSupervisor, KubeServices.Batteries, KubeServices.Supervisor, #PID<0.314.0>]\nMessage Queue Length: 0\nMessages: []\nLinks: [#PID<0.460.0>]\nDictionary: [rand_seed: {%{type: :exsss, next: #Function<0.40079776/1 in :rand.exsss_next>, bits: 58, uniform: #Function<1.40079776/1 in :rand.exsss_uniform>, uniform_n: #Function<2.40079776/2 in :rand.exsss_uniform>, jump: #Function<3.40079776/1 in :rand.exsplus_jump>}, [187180359115728669 | 36331262927685235]}]\nTrapping Exits: false\nStatus: :running\nHeap Size: 833026\nStack Size: 29\nReductions: 16465","time":"2024-10-14T01:08:31.903Z","metadata":{},"severity":"error"}
{"message":"Child KubeServices.ET.Usage of Supervisor {KubeServices.Batteries.Registry, \"batt_0192888c2ae37856afeb20d0fa308355\"} terminated\n** (exit) an exception was raised:\n    ** (MatchError) no match of right hand side value: {:error, :nxdomain}\n        (kube_services 0.24.0) lib/kube_services/et/usage.ex:48: KubeServices.ET.Usage.handle_info/2\n        (stdlib 6.1) gen_server.erl:2345: :gen_server.try_handle_info/3\n        (stdlib 6.1) gen_server.erl:2433: :gen_server.handle_msg/6\n        (stdlib 6.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3\nPid: #PID<0.462.0>\nStart Call: KubeServices.ET.Usage.start_link([home_client_pid: KubeServices.ET.HomeBaseClient])\nRestart: :permanent\nShutdown: 5000\nType: :worker","time":"2024-10-14T01:08:31.903Z","metadata":{},"severity":"error"}
{"message":"Child KubeServices.ET.Usage of Supervisor {KubeServices.Batteries.Registry, \"batt_0192888c2ae37856afeb20d0fa308355\"} started\nPid: #PID<0.940.0>\nStart Call: KubeServices.ET.Usage.start_link([home_client_pid: KubeServices.ET.HomeBaseClient])\nRestart: :permanent\nShutdown: 5000\nType: :worker","time":"2024-10-14T01:08:31.904Z","metadata":{},"severity":"info"}
{"message":"Checking on the status of the installation","time":"2024-10-14T01:08:59.534Z","metadata":{},"severity":"info"}
{"message":"Getting status","time":"2024-10-14T01:08:59.534Z","metadata":{},"severity":"debug"}
{"message":"Failed to get status: :nxdomain","time":"2024-10-14T01:08:59.590Z","metadata":{},"severity":"error"}
{"message":"Error checking the status of the installation: :nxdomain","time":"2024-10-14T01:08:59.590Z","metadata":{},"severity":"error"}

```

## Potential Fixes

- [x] #1028
- [x] #1029
- [ ] #1030

**Comment by elliottneilclark** [comment]
- [ ] Make sure the production home base URL is correct.
- [ ] Fix the path above not to crash, but set the status to error as expected
- [ ] consider a different supervisor tree structure that makes this not cascade?
